# Generated by Django 6.1.1 on 2026-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='days',
            field=models.BigIntegerField(default=1),
        ),
    ]
