# Generated by Django 6.1.1 on 2026-09-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_profile_total_bookings_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
